version: 2
jobs:
  build:
    working_directory: ~/xmlsigning
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          sudo apt-get update && sudo apt-get install -y xmlsec1
      - run:
          xmlsec1 --version
      - run:
          curl -sSL https://install.python-poetry.org | python -
      - run:
          $HOME/.local/bin/poetry install --no-ansi
      - run:
          $HOME/.local/bin/poetry run pytest
      - run:
          $HOME/.local/bin/poetry run black --check .
      - run:
          $HOME/.local/bin/poetry run isort --check-only .
      - run:
          $HOME/.local/bin/poetry run mypy src
